# Generated by Django 5.1 on 2024-09-02 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_venue', models.CharField(max_length=120, verbose_name='Venue name')),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=12, verbose_name='Contact Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=120, verbose_name='Event name')),
                ('date_event', models.DateTimeField(verbose_name='Event date')),
                ('manager_event', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, to='myevents.agendauser')),
                ('venue_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myevents.venue')),
            ],
        ),
    ]
